### ISSUE TITLE
ABI bug involving array in nested objects

### ISSUE THREAD

**Issue by ViliamVadocz** [LHolten/Volpe#42]
This issue is here just in case I forget.

code:
```
{[1, 2, 3], 1}, 2
```
expected output:
```
main() = {{[1, 2, 3], 1}, 2}
```
actual output:
```
main() = {{[1, 2, 3], 1}, 0}
```

**Comment by LHolten** [comment]
has been fixed in c6f4f5e18998aba7da9bae5809e149c3434761eb
